name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy to Azure Web App
      run: |
        git config --global user.name "Nour Ajoum"
        git config --global user.email "ajoumnour@outlook.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/NourAjoum/cicd-buzz.git
        git push origin main
